# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ximerix/Projects/demoqt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ximerix/Projects/demoqt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ximerix/Projects/demoqt/CMakeFiles /home/ximerix/Projects/demoqt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ximerix/Projects/demoqt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demoqt

# Build rule for target.
demoqt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demoqt
.PHONY : demoqt

# fast build rule for target.
demoqt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/build
.PHONY : demoqt/fast

#=============================================================================
# Target rules for targets named demoqt_autogen_timestamp_deps

# Build rule for target.
demoqt_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demoqt_autogen_timestamp_deps
.PHONY : demoqt_autogen_timestamp_deps

# fast build rule for target.
demoqt_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt_autogen_timestamp_deps.dir/build.make CMakeFiles/demoqt_autogen_timestamp_deps.dir/build
.PHONY : demoqt_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named demoqt_autogen

# Build rule for target.
demoqt_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 demoqt_autogen
.PHONY : demoqt_autogen

# fast build rule for target.
demoqt_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt_autogen.dir/build.make CMakeFiles/demoqt_autogen.dir/build
.PHONY : demoqt_autogen/fast

demoqt_autogen/mocs_compilation.o: demoqt_autogen/mocs_compilation.cpp.o
.PHONY : demoqt_autogen/mocs_compilation.o

# target to build an object file
demoqt_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/demoqt_autogen/mocs_compilation.cpp.o
.PHONY : demoqt_autogen/mocs_compilation.cpp.o

demoqt_autogen/mocs_compilation.i: demoqt_autogen/mocs_compilation.cpp.i
.PHONY : demoqt_autogen/mocs_compilation.i

# target to preprocess a source file
demoqt_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/demoqt_autogen/mocs_compilation.cpp.i
.PHONY : demoqt_autogen/mocs_compilation.cpp.i

demoqt_autogen/mocs_compilation.s: demoqt_autogen/mocs_compilation.cpp.s
.PHONY : demoqt_autogen/mocs_compilation.s

# target to generate assembly for a file
demoqt_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/demoqt_autogen/mocs_compilation.cpp.s
.PHONY : demoqt_autogen/mocs_compilation.cpp.s

src/database.o: src/database.cpp.o
.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/dbselectwindow.o: src/dbselectwindow.cpp.o
.PHONY : src/dbselectwindow.o

# target to build an object file
src/dbselectwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/dbselectwindow.cpp.o
.PHONY : src/dbselectwindow.cpp.o

src/dbselectwindow.i: src/dbselectwindow.cpp.i
.PHONY : src/dbselectwindow.i

# target to preprocess a source file
src/dbselectwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/dbselectwindow.cpp.i
.PHONY : src/dbselectwindow.cpp.i

src/dbselectwindow.s: src/dbselectwindow.cpp.s
.PHONY : src/dbselectwindow.s

# target to generate assembly for a file
src/dbselectwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/dbselectwindow.cpp.s
.PHONY : src/dbselectwindow.cpp.s

src/loginwindow.o: src/loginwindow.cpp.o
.PHONY : src/loginwindow.o

# target to build an object file
src/loginwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/loginwindow.cpp.o
.PHONY : src/loginwindow.cpp.o

src/loginwindow.i: src/loginwindow.cpp.i
.PHONY : src/loginwindow.i

# target to preprocess a source file
src/loginwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/loginwindow.cpp.i
.PHONY : src/loginwindow.cpp.i

src/loginwindow.s: src/loginwindow.cpp.s
.PHONY : src/loginwindow.s

# target to generate assembly for a file
src/loginwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/loginwindow.cpp.s
.PHONY : src/loginwindow.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/newuserdialog.o: src/newuserdialog.cpp.o
.PHONY : src/newuserdialog.o

# target to build an object file
src/newuserdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/newuserdialog.cpp.o
.PHONY : src/newuserdialog.cpp.o

src/newuserdialog.i: src/newuserdialog.cpp.i
.PHONY : src/newuserdialog.i

# target to preprocess a source file
src/newuserdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/newuserdialog.cpp.i
.PHONY : src/newuserdialog.cpp.i

src/newuserdialog.s: src/newuserdialog.cpp.s
.PHONY : src/newuserdialog.s

# target to generate assembly for a file
src/newuserdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/newuserdialog.cpp.s
.PHONY : src/newuserdialog.cpp.s

src/passwordhash.o: src/passwordhash.cpp.o
.PHONY : src/passwordhash.o

# target to build an object file
src/passwordhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/passwordhash.cpp.o
.PHONY : src/passwordhash.cpp.o

src/passwordhash.i: src/passwordhash.cpp.i
.PHONY : src/passwordhash.i

# target to preprocess a source file
src/passwordhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/passwordhash.cpp.i
.PHONY : src/passwordhash.cpp.i

src/passwordhash.s: src/passwordhash.cpp.s
.PHONY : src/passwordhash.s

# target to generate assembly for a file
src/passwordhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/passwordhash.cpp.s
.PHONY : src/passwordhash.cpp.s

src/tabletab.o: src/tabletab.cpp.o
.PHONY : src/tabletab.o

# target to build an object file
src/tabletab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/tabletab.cpp.o
.PHONY : src/tabletab.cpp.o

src/tabletab.i: src/tabletab.cpp.i
.PHONY : src/tabletab.i

# target to preprocess a source file
src/tabletab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/tabletab.cpp.i
.PHONY : src/tabletab.cpp.i

src/tabletab.s: src/tabletab.cpp.s
.PHONY : src/tabletab.s

# target to generate assembly for a file
src/tabletab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/demoqt.dir/build.make CMakeFiles/demoqt.dir/src/tabletab.cpp.s
.PHONY : src/tabletab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demoqt_autogen"
	@echo "... demoqt_autogen_timestamp_deps"
	@echo "... demoqt"
	@echo "... demoqt_autogen/mocs_compilation.o"
	@echo "... demoqt_autogen/mocs_compilation.i"
	@echo "... demoqt_autogen/mocs_compilation.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/dbselectwindow.o"
	@echo "... src/dbselectwindow.i"
	@echo "... src/dbselectwindow.s"
	@echo "... src/loginwindow.o"
	@echo "... src/loginwindow.i"
	@echo "... src/loginwindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/newuserdialog.o"
	@echo "... src/newuserdialog.i"
	@echo "... src/newuserdialog.s"
	@echo "... src/passwordhash.o"
	@echo "... src/passwordhash.i"
	@echo "... src/passwordhash.s"
	@echo "... src/tabletab.o"
	@echo "... src/tabletab.i"
	@echo "... src/tabletab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

